spring:
  application:
    name: zscat-manager-dubbo-consumer1
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/zscat-platform?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mapper/**/*Mapper.xml
  thymeleaf:
    mode: HTML
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*Mapper.xml
server:
  port: 9095

# Service version
manager:
  service:
    version: 1.0.0
dubbo:
  application:
    id: zscat-dubbo-consumer-id1
    name: zscat-dubbo-consumer-name1
  registry:
    protocol: zookeeper
    address: zookeeper://localhost:2181
    id: zscat-registry-1
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'


##七牛云的key
qiniu:
  accessKey: AMJ_CEvgX1eUYtSwC1ioo_WnmR73ufqYYmwrrPDV
  secretKey: 1iUDYRKdibiVP-WZLrGoErtdWWCqYWXjKUbQtAYQ
  bucketName:  j5shop
  basePath: http://p0bt2oaom.bkt.clouddn.com/

#日志配置
logging:
  level:
    com.zscat.platform.system.dao: debug
    org.springframework.hateoas: INFO
    org.springframework.data: INFO


