spring:
  application:
    name: zscat-label-dubbo-consumer1
server:
  port: 9091

# Service version
label:
  service:
    version: 1.0.0
dubbo:
  application:
    id: zscat-dubbo-consumer-id1
    name: zscat-dubbo-consumer-name1
  registry:
    protocol: zookeeper
    address: zookeeper://localhost:2181
    id: zscat-registry-1
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'
