server:
  port: 9098
spring:
  redis:
     database: 1
     host: 172.31.100.164
     port: 6379
     password: QM0t2ZRyjQU3
     timeout: 3000
     pool:
        max-active: 50
        max-wait: 3000
        max-idle: 10
        min-idle: 1
  datasource:
     name: test
     url: jdbc:mysql://localhost:3306/zscat-shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
     username: root
     password: root@123
     driver-class-name: com.mysql.jdbc.Driver
  mybatis:
     mapper-locations: classpath:mapper/*.xml

mybatis:
  mapper-locations: mapper/*.xml

dubbo:
  application.name: zscat-label-dubbo-provider
  protocol:
    name: dubbo
    port: 22185
    id: dubbo
    status: server
  registry:
    address: zookeeper://localhost:2181
    servers: localhost:22181
    id: zscat-label-registry-1
    sessionTimeoutMs: 30000
    syncTimeMs: 5000
    connectionTimeoutMs: 5000
    root: /config_center/
  application:
    name: zscat-label-dubbo-provider-name1
    id: zscat-label-dubbo-provider-id1
    qos-enable: true
    qos-port: 22222
  scan:
      basePackages: com.zscat.label.impl.service
  provider:
     timeout: 1000

management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'

#日志配置
logging:
  level:
    com.zscat.label.dao: debug
    org.springframework.hateoas: INFO
    org.springframework.data: INFO
label:
  service:
    version: 1.0.0