spring:
  module: blog
  profiles:
     active: dev
  redis:
     database: 1
     host: 172.31.100.164
     port: 6379
     password: QM0t2ZRyjQU3
     timeout: 3000
     pool:
        max-active: 50
        max-wait: 3000
        max-idle: 10
        min-idle: 1
  datasource:
     name: test
     url: jdbc:mysql://172.31.200.204:8066/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
     username: root
     password: root@123
     driver-class-name: com.mysql.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mapper/*.xml

mybatis:
  mapper-locations: mapper/*.xml

dubbo:
  application.name: dubbo-provider
  protocol:
    name: dubbo
    port: 22181
  registry:
    address: zookeeper://localhost:2181
    servers: localhost:22181
    sessionTimeoutMs: 30000
    syncTimeMs: 5000
    connectionTimeoutMs: 5000
    root: /config_center/
  provider:
     timeout: 1000



#日志配置
logging:
  level:
    com.zscat.blog.dao: INFO
    org.springframework.hateoas: INFO
    org.springframework.data: INFO